name: "Update unreleased section in CHANGELOG"
on:
  pull_request:
    # By default labeled/unlabeled are not included in the pull_request even so we need to list out what we want
    types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]

permissions:
  contents: read

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@204e7d3ef26579f4cd0fd759c57032656fdf23c7 # v3.6.1
        with:
          skipLabels: 'Skip-Changelog,dependencies,tests'
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v3.5.2
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # pin@v4
      - run: npx keep-a-changelog@2.5.3
      - run: |
          files=$(git status --porcelain)
          if [[ -n ${files}  ]]; then
            >&2 echo "Please run \`npx keep-a-changelog\` to fix changelog."
            >&2 echo ""
            >&2 echo "${files}"
            >&2 echo ""
            exit 1
          fi
