name: 'Comment on stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # pin@v8
        with:
          stale-issue-message: "It appears this issue has been stale for at least 14 days ğŸ—“ï¸. If no action is taken the maintainer team may consider closing the issue. Please reach out if you need feedback or follow up actions from the maintainer team."
          stale-pr-message: "It appears this PR has been stale for at least 14 days ğŸ—“ï¸. If no action is taken the maintainer team may consider closing the PR. Please reach out if you need assistance or help to finish the work ğŸ‘ğŸ¼."
          days-before-stale: 14
          days-before-close: -1
          days-before-issue-close: -1
          remove-issue-stale-when-updated: true
          remove-pr-stale-when-updated: true
